### ISSUE TITLE
Crash on Xcode 7

### ISSUE THREAD

**Issue by ArduinoEthernetController** [felix-dumit/FSDDropdownPicker#3]
On Xcode 6 everything worked fine. But if i run my project (only appears on a iDevice) via Xcode 7, the app crashes, every time as soon as i re-open the ViewController where i implemented the FSDDropdownPicker, with the following message in the console:
"Cannot form weak reference to instance (0x1455f9f00) of class FSDDropdownPicker. It is possible that this object was over-released, or is in the process of deallocation."
The queue tells me that there may be a problem with the deallocation and the Xcode 7 Compiler?
Thread 1:
5

```
[UITableView setDelegate:] 
-> 0x18906f678 <+308>:  mov    x0, x19 (rubbish just so you see)
```

6

```
[FSDDropDownPicker tableView] 
- (UITableView *)tableView { 
     [...]
     _tableView.delegate = self; //here EXC_REAKPOINT
}
```

7

```
[FSDDropdownPicker dealloc]
->
- (void)dealloc {
    self.tableView.delegate = nil; //here EXC_BREAKPOINT
    self.tableView.dataSource = nil;
}
```

8

```
[ViewController viewDidLoad:]
->
myPicker =  [self.navigationItem addDropdownPickerWithOptions:@[foo,bar]]; //again EXC_BREAKPOINT
```

I don`t know why this only appears when the project was build with Xcode 7.
But do you have any clue why this happens, and or know how to solve it? What is wrong with the delegate?
Would be a big help, thanks

**Comment by felix-dumit** [comment]
I have been using it in a project with Xcode 7 and it has been fine.
After (8) is myPicker being used anywhere else so it is retained? (is it declared with strong?) - maybe it is getting deallocated.

I'll play around to see if I can reproduce it also.

**Comment by ArduinoEthernetController** [comment]
Thanks for your fast reply :)
So, after

```
myPicker =  [self.navigationItem addDropdownPickerWithOptions:@[foo,bar]];
```

i use(also in viewDidLoad):

```
myPicker.displaysImageInList = NO;
myPicker.delegate = self;
```

and later in the code i implemented the two delegate methods

```
- (void)dropdownPicker:(FSDDropdownPicker *)dropdownPicker didDropDown:(BOOL)drop;
- (BOOL)dropdownPicker:(FSDDropdownPicker *)dropdownPicker didSelectOption:(id <FSDPickerItemProtocol> )option;
```

but i don`t use myPicker inside of them.

I came up with a solution to the problem after i read a post on stackoverflow about a similar problem:
Q:"If class A is using class B and class A is class B's delegate, is it ok if the delegate is set to nil in class B's dealloc?"
A:"You should set the classB's delegate property to nil in classA's dealloc."

I removed 

```
self.tableView.delegate = nil;
self.tableView.dataSource = nil;
```

from FSDDropdownPicker.m `s dealloc and put it into my viewControllers dealloc

```
myPicker.delegate = nil;
```

Now it works and does not crash... But i don`t really know if this is the right solution or just a messy workaround with a downside?
Thanks for your help

**Comment by felix-dumit** [comment]
I fixed a few crashes in the last commits
